language: node_js
node_js:
  - node
script:
  - npm test
  - npm run lint
  - npm run typescript
  - npm run build
  - echo "Folder name in Digital Ocean Spaces - $TRAVIS_COMMIT"
  - mkdir -p dist/devtools/$TRAVIS_COMMIT
  - mv dist/*.* dist/devtools/$TRAVIS_COMMIT/
deploy:
  provider: s3
  access_key_id: "$AMPATH_DIGITAL_OCEAN_SPACES_KEY_ID"
  secret_access_key: "$AMPATH_DIGITAL_OCEAN_SPACES_ACCESS_KEY"
  bucket: "$AMPATH_DIGITAL_OCEAN_SPACES_BUCKET"
  endpoint: "$AMPATH_DIGITAL_OCEAN_SPACES_ENDPOINT"
  cache-control: "max-age=31536000"
  local_dir: dist
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
after_deploy:
  - curl -u $AMPATH_DEPLOYER_USERNAME:$AMPATH_DEPLOYER_PASSWORD -d '{ "service":"@openmrs/devtools","url":"https://ampath-poc.fra1.digitaloceanspaces.com/devtools/'$TRAVIS_COMMIT'/devtools.js" }' -X PATCH $AMPATH_DEPLOYER_ENDPOINT/services\?env=prod -H "Accept:application/json" -H "Content-Type:application/json" --fail